version: "3"
services:
  data_visualisation:
    build:
      context: .
      dockerfile: Dockerfile
      network_mode: host
    environment:
      MODULE_NAME: data_visualisation
      EGRESS_URL: https://hookbin.com/lJjjGWVWkpUJ7ZEJWJxN
      INGRESS_HOST: 0.0.0.0
      INGRESS_PORT: 80
      INPUT_LABEL: "temperature"
      INPUT_UNIT: "Celsius"
      SAMPLE_SIZE: 10
      INSTANCE_INTERVAL: 3
      X_AXIS_LABEL: "Timestamp"
      Y_AXIS_LABEL: "Sensor Data"
      GRAPH_TITLE: "Sensor Data Graph"
      CHART_FILENAME: "graph.png"
    
    volumes:
      - /tmp/container_image:/app/image/src/app/save_image2
        
          
    ports:
      - 5000:80
