version: "3"
services:
  data_visualisation:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MODULE_NAME: data_visualisation
      EGRESS_URL: https://hookb.in/r1YwjDyn7BHzWWJVK8Gq
      INGRESS_HOST: 0.0.0.0
      INGRESS_PORT: 80
      INPUT_LABEL: "temperature"
      INPUT_UNIT: "Celsius"
      SAMPLE_SIZE: 100
      INSTANCE_INTERVAL: 3
      X_AXIS_LABEL: "Sensor Data"
      Y_AXIS_LABEL: "Timestamp"
      GRAPH_TITLE: "Sensor Data Graph"
      CHART_FILENAME: "graph.png"

    ports:
      - 5000:80